# Generated by Django 3.2.6 on 2022-09-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220922_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='technologies',
            new_name='tags',
        ),
    ]
